// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace mvc_4.Models
{
    public partial class book
    {
        [Key]
        public int id { get; set; }
        [StringLength(350)]
        public string title { get; set; }
        [StringLength(350)]
        public string bref { get; set; }
        public string desc { get; set; }
        public DateTime ?  date { get; set; }
        [StringLength(350)]
        public string photo { get; set; }
        public int? user_id { get; set; }
        public int? cat_id { get; set; }

        [ForeignKey("cat_id")]
        [InverseProperty("books")]
        public virtual Catalog cat { get; set; }
        [ForeignKey("user_id")]
        [InverseProperty("books")]
        public virtual User user { get; set; }
    }
}