// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace mvc_4.Models
{
    [Table("Catalog")]
    public partial class Catalog
    {
        public Catalog()
        {
            books = new HashSet<book>();
        }

        [Key]
        public int cat_id { get; set; }
        [StringLength(50)]
        public string cat_name { get; set; }
        public string cat_desc { get; set; }

        [InverseProperty("cat")]
        public virtual ICollection<book> books { get; set; }
    }
}