// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace mvc_4.Models
{
    [Table("User")]
    public partial class User
    {
        public User()
        {
            books = new HashSet<book>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "*")]
        public string name { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "*")]
        [MinLength(3)]
        public string username { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "*")]
        [EmailAddress(ErrorMessage = "invalid email")]
        public string email { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "*")]
        public string password { get; set; }
        [Required(ErrorMessage = "*")]
        [Compare("password", ErrorMessage = "password not match ")]
        [NotMapped]
        public string confirm_password { get; set; }
        public int? age { get; set; }

        [InverseProperty("user")]
        public virtual ICollection<book> books { get; set; }
    }
}